name: Check and Update GDAL Version

on:
  schedule:
    - cron: "0 0 1 * *" # 每月1日00:00 UTC运行
  workflow_dispatch: # 支持手动触发

jobs:
  check-gdal-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:ubuntugis/ppa
          sudo apt-get update

      - name: Check latest GDAL version
        id: get_version
        run: |
          LATEST_GDAL=$(apt-cache madison gdal-bin | grep -oP '\d+\.\d+\.\d+\+\S+' | head -1)
          echo "Latest GDAL version: $LATEST_GDAL"
          echo "gdal_version=$LATEST_GDAL" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            GDAL_VERSION=${{ steps.get_version.outputs.gdal_version }}
          push: true
          tags: freelabspace/cngeojdk:latest